base: 'https://mycocartotypo.ddev.site:8043/'
errorHandling:
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=10'
languages:
  -
    title: Français
    enabled: true
    languageId: 0
    base: /
    locale: fr_CH
    navigationTitle: Français
    flag: fr
    websiteTitle: ''
rootPageId: 1
websiteTitle: Mycocarto
