services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Feliciencorbat\Mycocarto\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Feliciencorbat\Mycocarto\Domain\Repository\EcologyRepository:
    public: true
